Wildcard enhancement, toggle read in order. 通配符增强，切换顺序读取
lllyasviel/Fooocus pull request #1761
Opened 2024-01-05 11:34 UTC by xhoxye

通配符增强，通过勾选切换通配符读取方法，默认不勾选为随机读取一行，勾选后为按顺序读取，并使用相同的种子。
![QQ截图20240105192916](https://github.com/lllyasviel/Fooocus/assets/129571231/adb33603-8a5f-4fba-8021-a44e9c587e09)
![QQ截图20240105192943](https://github.com/lllyasviel/Fooocus/assets/129571231/10f97a52-a310-43a4-93cb-ed75af6728ef)
![QQ截图20240105192953](https://github.com/lllyasviel/Fooocus/assets/129571231/a99deacd-c4fb-485d-93ae-dd911c2209d7)

2024-01-05 11:49 UTC, mashb1t commented
just for reference: achieves the same goal as https://github.com/lllyasviel/Fooocus/pull/1503 without having to explicitly prompt all the keywords

2024-01-05 12:11 UTC, mashb1t requested changes

2024-01-05 12:25 UTC, xhoxye commented
My English is not very good, I use translation software to dialogue, my code comments are to make myself understand, otherwise I may have to re-understand when I look back later

2024-01-05 13:06 UTC, mashb1t commented on modules/async_worker.py
> +# xhoxye
```suggestion
```

2024-01-05 13:09 UTC, mashb1t commented
@xhoxye no worries, that's why there are also community members who can support you there :)
For my part only one line is remaining to be changed as personal usernames as comments are not used throughout the code, but other than that the feature looks quite good and seems ready for code review by an authorised reviewer. I assume that this kind of MR falls into the category of "non-trivial changes" and may be reviewed by mid/end of January.

2024-01-06 17:40 UTC, LordMilutin commented
Any tips on how to use this? 
I see the checkbox for wildcards, I just don't know what formats to use in the prompt description box.
Can you give an example of 3 simple prompts?

2024-01-06 17:54 UTC, mashb1t approved these changes

2024-01-06 22:41 UTC, xhoxye commented
> the prompt description box

the prompt description box: __mylikeprompt__
Fooocus\wildcards\mylikeprompt.txt
mylikeprompt.txt
![QQ截图20240107063916](https://github.com/lllyasviel/Fooocus/assets/129571231/22cc213b-5d2e-4613-b5c8-9d44a4570912)
![QQ截图20240107063828](https://github.com/lllyasviel/Fooocus/assets/129571231/cdb388cc-0762-4efb-a7c7-6d8a4d576177)
![QQ截图20240107064039](https://github.com/lllyasviel/Fooocus/assets/129571231/e70f326a-f481-4601-9669-f16165d5a9a4)

2024-01-08 16:02 UTC, SerhiiSfr commented
Where is checkbox "upload mask"?????????!!!!!!

2024-01-08 17:43 UTC, SerhiiSfr commented
неу! Where is checkbox "upload mask"?????????!!!!!

2024-01-26 15:12 UTC, pacmanincarnate commented
In the spirit of keeping Fooocus more user-friendly, I'd recommend replacing the wildcard file reference with a text field in the UI that users can type or paste a list into for a wildcard. It's always kind of a pain to go back and forth between the app and the folder to remember what you named the wildcard file and likely edit one to suit your current needs.

2024-01-30 08:47 UTC, xhoxye commented
> In the spirit of keeping Fooocus more user-friendly, I'd recommend replacing the wildcard file reference with a text field in the UI that users can type or paste a list into for a wildcard. It's always kind of a pain to go back and forth between the app and the folder to remember what you named the wildcard file and likely edit one to suit your current needs.

Are you looking for this?
![QQ截图20240130164633](https://github.com/lllyasviel/Fooocus/assets/129571231/588ba8b4-1be0-45ac-87a2-63b721226c88)

![QQ截图20240130164645](https://github.com/lllyasviel/Fooocus/assets/129571231/9ace96d2-ee84-4534-991a-54e08d549e2f)

2024-03-10 22:18 UTC, merged

2024-03-14 08:12 UTC, bin862324915 commented
Previously, I used version 2.1.865 and it worked fine. However, after updating to version 2.2.1, I found that this feature was no longer available. Therefore, I added your code separately to the corresponding files, and when I started it, I clicked on the generate image to prompt for an error
`Traceback (most recent call last):
  File "E:\Program Files\Fooocus_win64_1-1-10\Fooocus\modules\async_worker.py", line 902, in worker
    handler(task)
  File "E:\Program Files\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Program Files\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Program Files\Fooocus_win64_1-1-10\Fooocus\modules\async_worker.py", line 215, in handler
    cn_tasks[cn_type].append([cn_img, cn_stop, cn_weight])
KeyError: 0.6
Total time: 0.03 seconds`
I don't know what went wrong, could you please help me

2024-03-14 08:14 UTC, mashb1t commented
this feature has been merged to develop and will be included in the next release. Feel free to directly check out develop so you don't accidentally miss something in the implementation.