Styles Grouping/Sorting #1770
lllyasviel/Fooocus pull request #1883
Opened 2024-01-11 18:49 UTC by hswlab

As described in https://github.com/lllyasviel/Fooocus/issues/1770#issuecomment-1887719446

2024-01-12 17:05 UTC, mashb1t requested changes
LGTM, just small code style changes

2024-01-12 17:05 UTC, mashb1t commented on css/style.css
> +                  }
Please adjust the style indent here:

```suggestion
.contain .tabs .tabitem.style_selections_tab {
  height: 100%;
}

.contain .tabs .tabitem.style_selections_tab > div:first-child {
  height: 100%;
}

.contain .tabs .tabitem.style_selections_tab .style_selections {
  min-height: 200px;
  height: 100%;
}

.contain .tabs .tabitem.style_selections_tab .style_selections .wrap[data-testid="checkbox-group"] {
  position: absolute; /* remove this to disable scrolling within the checkbox-group */
  overflow: auto;
  padding-right: 2px;
  max-height: 100%;
}

.contain .tabs .tabitem.style_selections_tab .style_selections .wrap[data-testid="checkbox-group"] label {
  /* max-width: calc(35% - 15px) !important; */ /* add this to enable 3 columns layout */
  flex: calc(50% - 5px) !important;
  padding: 2px 5px;
}

.contain .tabs .tabitem.style_selections_tab .style_selections .wrap[data-testid="checkbox-group"] label span {
  /* white-space:nowrap; */ /* add this to disable text wrapping (better choice for 3 columns layout) */
  overflow: hidden;
  text-overflow: ellipsis;
}
```

2024-01-12 17:05 UTC, mashb1t commented on javascript/script.js
> +
```suggestion
```

2024-01-13 09:42 UTC, hswlab commented
It's my first PR with review at github, I hope I didn't miss to click something ^^'.

2024-01-22 20:42 UTC, mashb1t approved these changes

2024-03-11 15:35 UTC, merged