Upgrade requirements_met function
lllyasviel/Fooocus pull request #1955
Opened 2024-01-17 08:17 UTC by Hunter-Houts

added more logging to see what goes wrong, helps fix random errors.

2024-01-17 22:17 UTC, mashb1t requested changes
Goood changes, just a small improvement

2024-01-18 00:06 UTC, Hunter-Houts commented
> Good changes, just a small improvement

Thanks! what changes are you requesting? (or am I misunderstanding?)

2024-01-18 00:14 UTC, mashb1t commented on modules/launch_util.py
> +import re
```suggestion
```

2024-01-20 01:53 UTC, Hunter-Houts commented
> I propose to replace regular expressions with [packaging.requirements.Requirement](https://packaging.pypa.io/en/stable/requirements.html)
> 
> Or... What is the purpose of `requirements_met`? Why couldn't we get rid of it entirely and call `pip install` every time unconditionally?

Thanks for the pointers! I've just pushed some changes to the PR, and here's the scoop on what I did:

1. **Switching to `packaging.requirements.Requirement`:**
   - You were spot on about using `Requirement`. It's in there now, and it's handling the version specs like a champ. It's way better for dealing with all those funky version formats in `requirements.txt`. Definitely a cleaner and more Pythonic way to go.

2. **About ditching `requirements_met`:**
   - Thought a lot about this one. I decided to keep it around for now. Mainly, it's there to keep things quick and light on network usage. It checks if we've already got the right stuff installed, so we don't waste time and bandwidth redoing `pip install`. It's kind of like, why go shopping if you’ve already got everything you need at home, right?
   - I get the appeal of just hammering `pip install` every time to keep it simple, but I’m playing the long game here for speed and efficiency.

Really appreciate your input – it kicked off some good changes. Check out the updated code and let me know what you think. Open to more ideas, always!

2024-01-26 02:47 UTC, Hunter-Houts commented
> Thanks for the changes.
> 
> I'm sorry for the second part of my comment. That was of course beyond the scope of the PR and it wasn't a complaint directed at you.
> 
> (I would also like to avoid potential doubts. I'm not a maintainer of the project)

No worries! :)

2024-01-26 02:49 UTC, Hunter-Houts commented
@mashb1t 
> Good changes, just a small improvement
Changes requested should be good to go now :) thank you for the suggestion!

2024-01-26 03:01 UTC, mashb1t approved these changes
lgtm 👍

2024-01-27 13:01 UTC, lllyasviel approved these changes

2024-01-27 13:01 UTC, merged