feature: Reads the size and ratio of the image and gives the recommended size
lllyasviel/Fooocus pull request #2971
Opened 2024-05-21 00:56 UTC by xhoxye

![QQ截图20240521085617](https://github.com/lllyasviel/Fooocus/assets/129571231/64e4f0d8-2165-4317-ba76-c703c182948e)

2024-05-21 15:04 UTC, mashb1t requested changes
@xhoxye thanks for contributing, will check this out in detail in a few hours. Please find one commend attached.

2024-05-21 15:04 UTC, mashb1t commented on webui.py
> +                                            ]
this could be modules.config.default_aspect_ratio or do you explicitly only want to recommend core SDXL resolutions?

2024-05-21 20:34 UTC, mashb1t commented
@xhoxye I've applied some adjustments, please check again

2024-05-21 21:40 UTC, mashb1t approved these changes

2024-05-22 00:09 UTC, xhoxye commented
Thank you very much for your help, although it is a little different from what I had in mind at the beginning, I initially wanted to recommend the standard size of SDXL

2024-05-22 18:40 UTC, mashb1t commented
@xhoxye thanks for the feedback, that's what i assumed in https://github.com/lllyasviel/Fooocus/pull/2971#discussion_r1608493765 and what makes the most sense.
My reasoning was that people might train LoRAs with specific aspect ratios or bucketing with other resolutions, but when the base model isn't trained these aspect ratios aren't the best choice anyways.
Users can still decide to just choose another available aspect ratio.

2024-05-22 18:47 UTC, merged

2024-05-24 13:34 UTC, xhoxye commented
I modified the use of textbox to display information to facilitate the translation of titles
![QQ截图20240524213242](https://github.com/lllyasviel/Fooocus/assets/129571231/8607c25d-15ea-4b7b-8dc4-ea98763236b2)
![QQ截图20240524213348](https://github.com/lllyasviel/Fooocus/assets/129571231/f284ff54-4687-4f7f-a1dc-a929492c0710)
`                                desc_image_size = gr.Textbox(label='Image Size and Recommended Size', elem_id='desc_image_size', visible=False)`

2024-05-24 14:15 UTC, mashb1t commented
Will include it in a few hours. Please add a new PR to develop if you want to be the author, if not i'll just cherry pick from your branch.